# Generated by Django 2.2.4 on 2019-10-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination1',
            new_name='Travello',
        ),
    ]
