# Generated by Django 2.2.4 on 2019-10-25 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_auto_20191024_2219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Travello',
            new_name='Destination1',
        ),
    ]
