# Generated by Django 2.2.4 on 2019-10-25 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_auto_20191025_0742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination1',
        ),
    ]
